### ISSUE TITLE
Compatibility check before release

### ISSUE THREAD

**Issue by ghost** [open-feature/java-sdk#46]
As we have more releases and some public API is already used by customers, will there be some checks in the release process such that we know public signatures or members are removed but they are public API?  Similarly, can the check reports potential compatiblity issue?

One solution is https://github.com/lvc/japi-compliance-checker
which compares the previous release jar and the snapshot jar you intend to release.
The report shows compatibility items for review.

Other ideas?

**Comment by justinabrahms** [comment]
cc @ejanei

**Comment by justinabrahms** [comment]
Can we maybe use this or something similar? Maybe a component of it? https://abi-laboratory.pro/

**Comment by ejanei** [comment]
I think so because https://abi-laboratory.pro/ uses the same [JAPICC japi-compliance-checker](https://github.com/lvc/japi-compliance-checker) according to https://abi-laboratory.pro/index.php?view=binary-compatibility

I'm just wondering what is extra in abi-laboratory but not in japi-compliance-checker.
