### ISSUE TITLE
Shutdown doesn't block

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk#683]
The `.shutdown()` method starts the shutdown in a new thread, and doesn't wait for its' completion. The net impact of this, is that the shutdown is hopefully finished _some time_ after the method is called.

I believe this somewhat undermines the purpose of the shutdown, which is to guaranty the cleanup of the provider, flushing telemetry, etc.

cc @kinyoklion @open-feature/sdk-java-maintainers @open-feature/sdk-java-approvers

**Comment by thisthat** [comment]
I would argue that this is not a bug since the spec doesn't say anything about the semantics of the method.
I believe having it async offers more possibilities to the Application developer. For example, I can call all the shutdowns of my frameworks in parallel and put a cap of 1s for them to finish before invoking `System.exit(0)`.
However, we need to implement also a method that notifies that a shutdown is completed. Something like `public boolean hasBeenShutdown()`.

**Comment by liran2000** [comment]
Whether it is async or not, I think the current implementation has to be fixed, as it is running as a [daemon](https://github.com/open-feature/java-sdk/blob/256d1156577c71097c38bc7393707f60e3dd12b7/src/main/java/dev/openfeature/sdk/ProviderRepository.java#L27), there is no guarantee or even best effort that it will finish.
If remaining async, it can be as default thread, with waiting a timeout of a few seconds before forcefully shutdown the thread pool.

* Similar for events.

**Comment by Kavindu-Dodan** [comment]
@liran2000 the reason for the task executor to use daemon threads is this bug https://github.com/open-feature/java-sdk/issues/600 . If not set daemon, threads can block the proper shutdown of an application. 

If we want the shutdown to block for acceptable timeout, then we can simply switch from `shutdown` to `awaitTermination` [1] 

[1] - https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html#awaitTermination-long-java.util.concurrent.TimeUnit-

**Comment by liran2000** [comment]
> @liran2000 the reason for the task executor to use daemon threads is this bug #600 . If not set daemon, threads can block the proper shutdown of an application.
> 
> If we want the shutdown to block for acceptable timeout, then we can simply switch from `shutdown` to `awaitTermination` [1]
> 
> [1] - https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html#awaitTermination-long-java.util.concurrent.TimeUnit-

Understood. Since you mentioned the _awaitTermination_ solution, [shutdownAndAwaitTermination](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html#awaitTermination-long-java.util.concurrent.TimeUnit-) can fit.

For bug #600 possibly together with solution to this issue, may consider separate thread pool for shutdown task.

I think first need to decide and define at spec / doc shutdown should block or not, and then proceed to the solution accordingly.

The solution requirement would be then cleanup of the provider, flushing telemetry, etc. at best effort up to a timeout at least.

**Comment by toddbaert** [comment]
> I think first need to decide and define at spec / doc shutdown should block or not, and then proceed to the solution accordingly.

I think the purpose outlined in the spec makes it implicit this method should block in the Java case. We could add specific language around that in the spec, but it would have to be something more vague like "it should be possible to await the termination of the shutdown", since blocking isn't always the right term (for async languages like JS, for instance).

> The solution requirement would be then cleanup of the provider, flushing telemetry, etc. at best effort up to a timeout at least.

We could mention a timeout in a non-normative section... it could be an optional param.

**Comment by jarebudev** [comment]
I'm happy to have a look at this one

**Comment by toddbaert** [comment]
> I'm happy to have a look at this one

Thanks @jarebudev , assigned!
